# -*- coding: utf-8 -*-
"""TRABALHO CLASSIFICADORES

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11cGNvR8i0PGZO0Mh-SbuqTQuY6PTccHp

# **Atividade de Classificadores**

## O problema e a variável-alvo

O dataset escolhido foi o **Telco Customer Churn - Retenção de Clientes**. Ele contém dados relevantes de clientes de empresa(s) do ramo de telecomunicações. A partir dos dados é possível analisar e prever o comportamento para reter clientes.

Dessa forma, a **variável alvo** é justamente a coluna de **cancelamento do serviço ("Churn")**, que indica a não retenção do cliente.

 O dataset escolhido veio do Kaggle, [neste link](https://www.kaggle.com/datasets/blastchar/telco-customer-churn/data).


 Desenvolvi o trabalho me baseando nas atividades:

 * LE01_Exercicios_Vamos_praticar!!! [aqui](https://colab.research.google.com/drive/1zswvyheh6tRD75AP5UCoRfCZ0LW1gDIt?authuser=1&usp=drive_open#scrollTo=i3mFb2qDf_d4)

* Predição para Doença Cardíaca [aqui](https://colab.research.google.com/drive/10oRytMZjzt4hGPBJuXffY9C8aZLEORmy?authuser=1#scrollTo=YWK_i_CQfdsT)

## Sumário

1. Importar e visualizar os dados
2. Avaliar a qualidade dos dados
3. Limpeza e preparação dos dados
4. Avaliar o comportamento das variáveis
5. Separar X e Y
6. Dividir treino e teste
7. Treinar e avaliar os classificadores
8. Comparar os modelos com 5-fold Cross Validation
9. Refinar modelos e ajustar hiperparâmetros
10. Conclusão

## **Passo 1: Importar e visualizar os dados**
Objetivo: Ler e exibir informações básicas de um dataset.

● Baixar um dataset em formato .csv ou .xlsx

● Exibir as primeiras 10 linhas do dataset utilizando df.head().
"""

# ==============================
# Passo 1: Importar e visualizar os dados
# ==============================

from google.colab import drive
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm

from sklearn.model_selection import (
    train_test_split,
    cross_val_score,
    StratifiedKFold,
    GridSearchCV,
)
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC

# Montar o Google Drive no Colab
drive.mount('/content/drive')

# Definir o caminho do dataset
data_path = '/content/drive/MyDrive/Colab Notebooks/classificadores-customer-chrun/WA_Fn-UseC_-Telco-Customer-Churn.csv'

# Carregar o dataset
data = pd.read_csv(data_path)

print("Primeiras 10 linhas:")
print(data.head(10))
print('-----------------------')

print("Contagem da variável-alvo:")
print(data['Churn'].value_counts())
print('-----------------------')

print("Percentual da variável-alvo:")
print(data['Churn'].value_counts(normalize=True) * 100)
print('-----------------------')

"""# Análise de Dados

**Atributos do Dataset:**

| Atributo | Tradução | Respostas  |
| :--- | :--- | :--- |
| **customerID** | ID do Cliente | Identificador único de cada cliente. |
| **gender** | Sexo | Female (Mulher), Male (Homem). |
| **SeniorCitizen** | Idoso | 0 (Não), 1 (Sim). |
| **Partner** | Parceiro | Yes , No |
| **Dependents** | Dependentes | Yes , No  |
| **tenure** | Meses de Contrato | Número de meses que o cliente permaneceu na empresa. |
| **PhoneService** | Serviço Telefônico | Yes , No . |
| **MultipleLines** | Múltiplas Linhas | Yes , No , No phone service. |
| **InternetService** | Serviço de Internet | DSL, Fiber optic, No . |
| **OnlineSecurity** | Segurança Online | Yes, No, No internet service. |
| **OnlineBackup** | Backup Online | Yes, No, No internet service. |
| **DeviceProtection** | Proteção de Dispositivo | Yes, No, No internet service. |
| **TechSupport** | Suporte Técnico | Yes, No, No internet service. |
| **StreamingTV** | Streaming de TV | Yes, No, No internet service. |
| **StreamingMovies** | Streaming de Filmes | Yes, No, No internet service. |
| **Contract** | Contrato | Month-to-month (Mensal), One year (Um ano), Two year (Dois anos). |
| **PaperlessBilling** | Fatura Digital | Yes , No. |
| **PaymentMethod** | Método de Pagamento | Electronic check, Mailed check, Bank transfer (automatic), Credit card (automatic). |
| **MonthlyCharges** | Valor Mensal | O valor cobrado do cliente mensalmente. |
| **TotalCharges** | Valor Total | O valor total cobrado do cliente. |
| **Churn** | Cancelamento (Alvo - indica se o cliente deixou a empresa) | Yes, No . |

## **Passo 2: Avaliar a qualidade dos dados**
Objetivo: Entender a base antes de mexer nela

● Exibir quantidade de linhas, colunas, tipos de dados e valores nulos.
"""

# ==============================
# Passo 2: Avaliar a qualidade dos dados
# ==============================

#Verificando a quantidade de registros
# (linhas , colunas)
data.shape

data.info()

data.describe()

# Verificação de Valores Nulos
null_values = data.isnull().sum()
print("Valores Nulos: \n", null_values)
print('\n -----------------------')

# Verificação de Tipos de Dados
data_types = data.dtypes
print("Tipos de Dados:\n", data_types)
print('-----------------------')

"""**Conclusão:**

O dataset possui 21 variáveis, numéricas ou categóricas, mas **nem todas estão prontas para a aplicação direta dos algoritmos de classificação**.

A **TotalCharges** deverá ser convertida para tipo **numérico** (float64), pois atualmente está como object, embora represente valores numéricos;

A **customerID** deverá ser **removida**, por não contribuir para a predição;

As variáveis **categóricas**, incluindo a variável alvo Churn, precisarão ser transformadas em valores **numéricos** (int64), já que os classificadores trabalham com dados em formato numérico.

Essas conversões serão feitas na etapa de Limpeza e Preparação dos Dados.

## **Passo 3:  Limpeza e preparação dos dados**
Objetivo: Realizar o tratamento de valores nulos, correção de tipos e remoção de duplicatas para deixar o dataset adequado
para a a análise e posteriormente a aplicação dos algoritmos de classificação

● Remover colunas que não contribuem para a predição

● Verificar e corrigir tipos dos dados

● Verificar e preencher/remover nulos

*   Para variáveis numéricas: substitua valores nulos pela média ou mediana.
*   Para variáveis categóricas: substitua os valores nulos pela moda (valor mais frequente).

● Verificar e remover duplicatas

● Revisar e aplicar encoding

● Avaliar se será necessário aplicar escalonamento
"""

# ==============================
# Passo 3: Limpeza e preparação dos dados
# ==============================

# Criando uma cópia do dataset original para preparar os dados
data_prep = data.copy()

"""### 3.1 Remover colunas que não contribuem para a predição"""

# Removendo a coluna identificadora
data_prep = data_prep.drop("customerID", axis=1)

"""### 3.2 Corrigir tipos de dados"""

print("Tipos de dados antes da conversão:")
print(data_prep.dtypes)
print('-----------------------')

# Convertendo TotalCharges de object para float64
data_prep["TotalCharges"] = pd.to_numeric(data_prep["TotalCharges"], errors="coerce")

"""### 3.3 Verificar e tratar valores nulos"""

# Verificando valores nulos após a conversão
print("Valores nulos após a conversão de TotalCharges:")
print(data_prep.isnull().sum())
print('-----------------------')

# Preenchendo os nulos de TotalCharges com a mediana
data_prep["TotalCharges"] = data_prep["TotalCharges"].fillna(data_prep["TotalCharges"].median())

# Conferindo novamente
print("Valores nulos após o tratamento:")
print(data_prep.isnull().sum())
print('-----------------------')

"""### 3.4 Verificar e remover duplicatas"""

# Verificando registros duplicados
duplicados = data_prep.duplicated().sum()
print(f"Quantidade de registros duplicados: {duplicados}")
print('-----------------------')

# Removendo duplicatas, se existirem
data_prep = data_prep.drop_duplicates()

print("Dimensão da base após remoção de duplicatas:")
print(data_prep.shape)
print('-----------------------')

"""### 3.5 Revisar e aplicar encoding"""

# Convertendo variáveis categóricas para valores numéricos nas mesmas colunas
data_prep["gender"] = data_prep["gender"].map({"Female": 0, "Male": 1}).astype("int64")
data_prep["Partner"] = data_prep["Partner"].map({"No": 0, "Yes": 1}).astype("int64")
data_prep["Dependents"] = data_prep["Dependents"].map({"No": 0, "Yes": 1}).astype("int64")
data_prep["PhoneService"] = data_prep["PhoneService"].map({"No": 0, "Yes": 1}).astype("int64")

data_prep["MultipleLines"] = data_prep["MultipleLines"].map({
    "No": 0,
    "Yes": 1,
    "No phone service": 2
}).astype("int64")

data_prep["InternetService"] = data_prep["InternetService"].map({
    "DSL": 0,
    "Fiber optic": 1,
    "No": 2
}).astype("int64")

data_prep["OnlineSecurity"] = data_prep["OnlineSecurity"].map({
    "No": 0,
    "Yes": 1,
    "No internet service": 2
}).astype("int64")

data_prep["OnlineBackup"] = data_prep["OnlineBackup"].map({
    "No": 0,
    "Yes": 1,
    "No internet service": 2
}).astype("int64")

data_prep["DeviceProtection"] = data_prep["DeviceProtection"].map({
    "No": 0,
    "Yes": 1,
    "No internet service": 2
}).astype("int64")

data_prep["TechSupport"] = data_prep["TechSupport"].map({
    "No": 0,
    "Yes": 1,
    "No internet service": 2
}).astype("int64")

data_prep["StreamingTV"] = data_prep["StreamingTV"].map({
    "No": 0,
    "Yes": 1,
    "No internet service": 2
}).astype("int64")

data_prep["StreamingMovies"] = data_prep["StreamingMovies"].map({
    "No": 0,
    "Yes": 1,
    "No internet service": 2
}).astype("int64")

data_prep["Contract"] = data_prep["Contract"].map({
    "Month-to-month": 0,
    "One year": 1,
    "Two year": 2
}).astype("int64")

data_prep["PaperlessBilling"] = data_prep["PaperlessBilling"].map({
    "No": 0,
    "Yes": 1
}).astype("int64")

data_prep["PaymentMethod"] = data_prep["PaymentMethod"].map({
    "Electronic check": 0,
    "Mailed check": 1,
    "Bank transfer (automatic)": 2,
    "Credit card (automatic)": 3
}).astype("int64")

data_prep["Churn"] = data_prep["Churn"].map({
    "No": 0,
    "Yes": 1
}).astype("int64")

"""### 3.6 Avaliar se será necessário aplicar escalonamento"""

print("Tipos de dados após a preparação:")
print(data_prep.dtypes)
print('-----------------------')

print("Estatísticas descritivas da base preparada:")
print(data_prep.describe())
print('-----------------------')

"""### 3.7 Gerar a base final preparada"""

print("Dimensão final da base preparada:")
print(data_prep.shape)
print('-----------------------')

print("Primeiras 5 linhas da base preparada:")
print(data_prep.head())

"""**Atributos do Dataset após o pré-processamento:**

| Atributo | Tradução | Respostas / Conversão Aplicada |
| :--- | :--- | :--- |
| **gender** | Sexo | **0 = Female (Mulher), 1 = Male (Homem)** |
| **SeniorCitizen** | Idoso | **0 = Não, 1 = Sim** |
| **Partner** | Parceiro | **0 = No, 1 = Yes** |
| **Dependents** | Dependentes | **0 = No, 1 = Yes** |
| **tenure** | Meses de Contrato | Número de meses que o cliente permaneceu na empresa. |
| **PhoneService** | Serviço Telefônico | **0 = No, 1 = Yes** |
| **MultipleLines** | Múltiplas Linhas | **0 = No, 1 = Yes, 2 = No phone service** |
| **InternetService** | Serviço de Internet | **0 = DSL, 1 = Fiber optic, 2 = No** |
| **OnlineSecurity** | Segurança Online | **0 = No, 1 = Yes, 2 = No internet service** |
| **OnlineBackup** | Backup Online | **0 = No, 1 = Yes, 2 = No internet service** |
| **DeviceProtection** | Proteção de Dispositivo | **0 = No, 1 = Yes, 2 = No internet service** |
| **TechSupport** | Suporte Técnico | **0 = No, 1 = Yes, 2 = No internet service** |
| **StreamingTV** | Streaming de TV | **0 = No, 1 = Yes, 2 = No internet service** |
| **StreamingMovies** | Streaming de Filmes | **0 = No, 1 = Yes, 2 = No internet service** |
| **Contract** | Contrato | **0 = Month-to-month (Mensal), 1 = One year (Um ano), 2 = Two year (Dois anos)** |
| **PaperlessBilling** | Fatura Digital | **0 = No, 1 = Yes** |
| **PaymentMethod** | Método de Pagamento | **0 = Electronic check, 1 = Mailed check, 2 = Bank transfer (automatic), 3 = Credit card (automatic)** |
| **MonthlyCharges** | Valor Mensal | O valor cobrado do cliente mensalmente. |
| **TotalCharges** | Valor Total | Convertido de **object** para **float64**, representando o valor total cobrado do cliente. |
| **Churn** | Cancelamento (Alvo - indica se o cliente deixou a empresa) | **0 = No, 1 = Yes** |

**Conclusão:**

Nesta etapa, o dataset foi limpo e preparado para as próximas fases da análise e da modelagem. A coluna customerID foi removida por não contribuir para a predição, e a coluna TotalCharges, que estava armazenada como object, foi convertida para float64. Após essa conversão, surgiram valores nulos, que foram tratados com o preenchimento pela mediana da própria coluna.

Também foi realizada a verificação de registros duplicados, com o objetivo de evitar que observações repetidas influenciassem indevidamente a análise e o treinamento dos modelos. Além disso, as variáveis categóricas foram convertidas para valores numéricos inteiros, mantendo as colunas originais, o que foi necessário para permitir a aplicação dos algoritmos de classificação.

Ao final, observou-se que a base passou a conter apenas atributos numéricos e ficou adequada para as próximas etapas do trabalho. Também foi possível identificar que algumas variáveis apresentam escalas diferentes, como tenure, MonthlyCharges e TotalCharges, o que indica que poderá ser necessário aplicar escalonamento mais adiante, especialmente em modelos sensíveis à escala, como KNN e SVM.

## **Passo 4: Avaliar o comportamento das variáveis**
Objetivo: Realziar uma análise exploratória dos dados e observar a distribuição, relação entre variáveis, possíveis outliers e correlação com a target (Churn)

● Utilizar histogramas, boxplots, pairplot,
countplot da variável-alvo, correlação / heatmap
"""

# ==============================
# Passo 4: Avaliar o comportamento das variáveis
# ==============================

# Distribuição das Variáveis utilizando Histogramas
data_prep.hist(bins=10, figsize=(20, 18))
plt.tight_layout()
plt.show()

# Countplot da variável-alvo
plt.figure(figsize=(6, 4))
sns.countplot(x='Churn', data=data_prep)
plt.title('Distribuição da variável-alvo Churn')
plt.show()

# Relação entre os pares de variáveis do Dataset através do pairplot
sns.pairplot(data_prep, hue='Churn')
plt.show()

# Relação entre os pares de variáveis de interesse do Dataset através do pairplot
sns.pairplot(
    data_prep,
    hue='Churn',
    vars=['tenure', 'MonthlyCharges', 'TotalCharges', 'SeniorCitizen', 'Partner', 'Dependents', 'Contract', 'PaperlessBilling', 'PaymentMethod' ]
)
plt.show()

"""**Conclusão:**

O pairplot permite observar a relação entre as principais variáveis numéricas do dataset em função da variável-alvo Churn.

Nota-se que clientes com menor tempo de permanência (tenure) parecem apresentar maior concentração de cancelamentos, e que MonthlyCharges e TotalCharges também apresentam comportamentos distintos entre clientes que cancelaram e os que permaneceram.

"""

# Distribuição das Variáveis utilizando Boxplots
plt.figure(figsize=(20, 10))
data_prep.boxplot(
    column=[
        'gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
        'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
        'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
        'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
        'MonthlyCharges', 'TotalCharges', 'Churn'
    ],
    grid=True,
    rot=45
)
plt.show()

plt.figure(figsize=(12, 6))
data_prep.boxplot(column=['tenure', 'MonthlyCharges'], grid=True)
plt.show()

plt.figure(figsize=(12, 6))
data_prep.boxplot(column=['TotalCharges'], grid=True)
plt.show()

"""**Conclusão:**

Os boxplots das variáveis numéricas mostram a dispersão dos dados e a presença de possíveis valores extremos.

A variável TotalCharges apresenta maior amplitude e dispersão, enquanto tenure e MonthlyCharges também mostram distribuição heterogênea, o que indica a existência de perfis diferentes de clientes na base.

#Verificação de outliers com z-score (com 3 desvios padrão)
"""

# Função para visualização do z-score
def zscore_visualization(dataframe, column, zscores, outliers):
    plt.figure(figsize=(8, 4))
    plt.hist(zscores, bins=30, density=True, alpha=0.6, color='#70a288', label='Z-Scores')

    x = np.linspace(zscores.min(), zscores.max(), 100)
    plt.plot(x, norm.pdf(x), 'r-', label='Curva Normal')

    plt.axvline(-3, color='r', linestyle='--', label='Threshold')
    plt.axvline(3, color='r', linestyle='--')
    plt.scatter(outliers, np.zeros(len(outliers)), color='red', label='Outliers')

    plt.xlabel('Z-Score')
    plt.ylabel('Densidade')
    plt.title(f'Distribuição Z-Score de {column} com curva normal')
    plt.text(
        0.02,
        0.9,
        f'Outliers: {len(outliers)}',
        transform=plt.gca().transAxes,
        bbox=dict(facecolor='white', edgecolor='black', boxstyle='square')
    )
    plt.legend()
    plt.grid(True)
    plt.show()

# Detecção de outliers (mantendo base com e sem outliers)
data_copy = data_prep.copy()
numeric_cols = ['tenure', 'MonthlyCharges', 'TotalCharges']
outliers_summary = {}
outlier_mask = pd.Series(False, index=data_copy.index)

for col in numeric_cols:
    zscores = (data_copy[col] - data_copy[col].mean()) / data_copy[col].std()
    current_mask = (zscores < -3) | (zscores > 3)
    outliers_summary[col] = int(current_mask.sum())
    outlier_mask = outlier_mask | current_mask

    print(f"Quantidade de outliers em {col}: {int(current_mask.sum())}")
    zscore_visualization(data_copy, col, zscores, zscores[current_mask])

print("Resumo de outliers encontrados:")
print(outliers_summary)
print('-----------------------')

total_linhas_com_outlier = int(outlier_mask.sum())
print(f"Total de linhas com pelo menos um outlier: {total_linhas_com_outlier}")
print('-----------------------')

# Base sem outliers para comparação e refinamento posterior
data_no_outliers = data_copy.loc[~outlier_mask].copy()

print("Dimensão da base COM outliers:", data_prep.shape)
print("Dimensão da base SEM outliers:", data_no_outliers.shape)
print('-----------------------')

if data_prep.shape == data_no_outliers.shape:
    print("Conclusão: não foram encontrados outliers nas variáveis analisadas pelo critério de z-score (|z| > 3).")
    print("Assim, a base sem outliers é idêntica à base original e não foi necessário realizar remoção de registros.")
    print('-----------------------')
else:
    print("Conclusão: foram encontrados outliers e a base sem outliers será utilizada para comparação.")
    print('-----------------------')

"""**Conclusão**

Foi realizada a detecção de outliers nas variáveis numéricas contínuas tenure, MonthlyCharges e TotalCharges, utilizando o critério de z-score com limite de 3 desvios padrão.

No entanto, não foram identificados registros com valores acima desse limite nas variáveis analisadas. Dessa forma, não houve necessidade de tratamento ou remoção de outliers nesta base.

Assim, a base sem outliers permaneceu com a mesma dimensão da base original, indicando que, para este dataset e para o critério adotado, os valores observados podem ser considerados compatíveis com a distribuição dos dados.

**Análise de Correlação**
"""

# Análise de Correlações
# Podemos usar a função corr() para calcular a correlação entre as variáveis numéricas
numerical_data = data_prep.select_dtypes(include=['number'])
correlation_matrix = numerical_data.corr()
print(correlation_matrix)

plt.figure(figsize=(14, 10))
sns.heatmap(correlation_matrix, annot=True, fmt=".1f", cmap="coolwarm")
plt.show()

"""**Conclusão:**

O mapa de calor mostra a correlação entre as variáveis numéricas do dataset.

Em relação à variável-alvo Churn, algumas variáveis apresentam associação mais perceptível, especialmente tenure, Contract, OnlineSecurity, TechSupport e TotalCharges, o que indica que esses atributos podem ser relevantes para o treinamento dos classificadores.

## **Passo 5: Separar X e Y**
Objetivo: Separar as variáveis explicativas da variável alvo para preparar os dados para o treinamento dos modelos.

● X: conjunto de atributos utilizados para prever o cancelamento

● y: variável alvo (Churn)
"""

# ==============================
# Passo 5: Separar X e Y
# ==============================

y = data_prep['Churn']
X = data_prep.drop('Churn', axis=1)

print("Dimensão de X:", X.shape)
print("Dimensão de y:", y.shape)
print('-----------------------')

print("Primeiras 5 linhas de X:")
print(X.head())
print('-----------------------')

print("Primeiras 5 linhas de y:")
print(y.head())
print('-----------------------')

"""**Conclusão:**

Nesta etapa, a base preparada foi separada em variáveis de entrada (X) e variável alvo (y).

As variáveis de entrada correspondem aos atributos dos clientes, enquanto a variável alvo Churn representa se o cliente cancelou ou não o serviço.
Essa separação é necessária para que os classificadores possam ser treinados e avaliados corretamente nas próximas etapas.

## **Passo 6: Dividir treino e teste**
Objetivo: Separar os dados em conjuntos de treino e teste para permitir a avaliação dos classificadores em dados que não foram utilizados no treinamento.

● X_train e y_train: usados para treinar os modelos

● X_test e y_test: usados para testar os modelos
"""

# ==============================
# Passo 6: Dividir treino e teste
# ==============================

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.3,
    random_state=42,
    stratify=y
)

print("Dimensão de X_train:", X_train.shape)
print("Dimensão de X_test:", X_test.shape)
print("Dimensão de y_train:", y_train.shape)
print("Dimensão de y_test:", y_test.shape)
print('-----------------------')

print("Distribuição de y_train:")
print(y_train.value_counts(normalize=True) * 100)
print('-----------------------')

print("Distribuição de y_test:")
print(y_test.value_counts(normalize=True) * 100)
print('-----------------------')

# Escalonamento
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""**Conclusão:**

Nesta etapa, os dados foram divididos em conjuntos de treino e teste, permitindo que os modelos sejam treinados em uma parte da base e avaliados em outra parte que não foi vista anteriormente.

Foi utilizada a proporção de 70% para treino e 30% para teste, com estratificação da variável alvo, de forma a manter proporções semelhantes de clientes que cancelaram e que não cancelaram o serviço em ambos os conjuntos.

## **Passo 7: Treinar e avaliar os classificadores**

Objetivo: Treinar os modelos de classificação e avaliar seus desempenhos com base no conjunto de teste.

● Regressão Logística

● Árvore de Decisão

● K-Nearest Neighbor

● Random Forest

● Support Vector Machine

Nesta etapa, também será aplicado escalonamento nos dados para os modelos sensíveis à escala.
"""

# ==============================
# Passo 7: Treinar e avaliar os classificadores
# ==============================

# Função auxiliar de avaliação
def avaliar_modelo(nome_modelo, modelo, X_tr, X_te, y_tr, y_te):
    modelo.fit(X_tr, y_tr)
    y_pred = modelo.predict(X_te)

    accuracy = accuracy_score(y_te, y_pred)
    report = classification_report(y_te, y_pred, zero_division=0)
    matrix = confusion_matrix(y_te, y_pred)

    print(f"Acurácia ({nome_modelo}): {accuracy:.4f}")
    print(f"Relatório de Classificação ({nome_modelo}):")
    print(report)
    print(f"Matriz de Confusão ({nome_modelo}):")
    print(matrix)
    print('-----------------------')

    return accuracy, report, matrix

"""### **7.1 Árvore de Decisão**"""

# 7.1 Árvore de Decisão
dt_model = DecisionTreeClassifier(random_state=42)
accuracy_dt, classification_rep_dt, conf_matrix_dt = avaliar_modelo(
    'Árvore de Decisão',
    dt_model,
    X_train,
    X_test,
    y_train,
    y_test,
)

"""### **7.2 K-Nearest Neighbor**"""

# 7.3 K-Nearest Neighbor
knn_model = KNeighborsClassifier()
accuracy_knn, classification_rep_knn, conf_matrix_knn = avaliar_modelo(
    'K-Nearest Neighbor',
    knn_model,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test,
)

"""### **7.3 Random Forest**"""

# 7.3 Random Forest
rf_model = RandomForestClassifier(random_state=42)
accuracy_rf, classification_rep_rf, conf_matrix_rf = avaliar_modelo(
    'Random Forest',
    rf_model,
    X_train,
    X_test,
    y_train,
    y_test,
)

"""### **7.4 Support Vector Machine**"""

# 7.4 Support Vector Machine
svm_model = SVC(random_state=42)
accuracy_svm, classification_rep_svm, conf_matrix_svm = avaliar_modelo(
    'Support Vector Machine',
    svm_model,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test,
)

"""## **Passo 8: Comparar os modelos com 5-fold Cross Validation**
Objetivo: Comparar o desempenho dos classificadores utilizando 5-fold Cross Validation.
"""

# ==============================
# Passo 8: Comparar os modelos com 5-fold Cross Validation
# ==============================

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

pipeline_dt = Pipeline([
    ('model', DecisionTreeClassifier(random_state=42))
])

pipeline_knn = Pipeline([
    ('scaler', StandardScaler()),
    ('model', KNeighborsClassifier())
])

pipeline_rf = Pipeline([
    ('model', RandomForestClassifier(random_state=42))
])

pipeline_svm = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SVC(random_state=42))
])

scores_dt = cross_val_score(pipeline_dt, X, y, cv=cv, scoring='accuracy')
scores_knn = cross_val_score(pipeline_knn, X, y, cv=cv, scoring='accuracy')
scores_rf = cross_val_score(pipeline_rf, X, y, cv=cv, scoring='accuracy')
scores_svm = cross_val_score(pipeline_svm, X, y, cv=cv, scoring='accuracy')

print("Acurácias por fold - Árvore de Decisão:", scores_dt)
print("Média da Árvore de Decisão:", scores_dt.mean())
print('-----------------------')

print("Acurácias por fold - K-Nearest Neighbor:", scores_knn)
print("Média do K-Nearest Neighbor:", scores_knn.mean())
print('-----------------------')

print("Acurácias por fold - Random Forest:", scores_rf)
print("Média do Random Forest:", scores_rf.mean())
print('-----------------------')

print("Acurácias por fold - Support Vector Machine:", scores_svm)
print("Média do Support Vector Machine:", scores_svm.mean())
print('-----------------------')

models_cv = [
    'Árvore de Decisão',
    'K-Nearest Neighbor',
    'Random Forest',
    'Support Vector Machine'
]

mean_accuracies = [
    scores_dt.mean(),
    scores_knn.mean(),
    scores_rf.mean(),
    scores_svm.mean()
]

plt.figure(figsize=(12, 6))
plt.bar(models_cv, mean_accuracies)
plt.xlabel('Modelos')
plt.ylabel('Acurácia Média (5-fold CV)')
plt.title('Comparação dos Modelos com 5-fold Cross Validation')
plt.xticks(rotation=20)

for idx, val in enumerate(mean_accuracies):
    plt.text(idx, val, f'{val:.4f}', ha='center', va='bottom')

plt.ylim(0, 1)
plt.show()

"""**Conclusão:**

A comparação entre os classificadores foi realizada por meio de validação cruzada com 5 folds, conforme exigido na atividade. Esse procedimento permite uma avaliação mais confiável dos modelos, pois cada classificador é treinado e testado em diferentes divisões da base de dados, reduzindo a influência de uma única separação entre treino e teste.

Com base nas médias de acurácia obtidas nos cinco folds, a classificação dos modelos ficou da seguinte forma:

1. **Support Vector Machine** — média de **0,8016**
2. **Random Forest** — média de **0,7909**
3. **K-Nearest Neighbor** — média de **0,7606**
4. **Árvore de Decisão** — média de **0,7251**

Os resultados por fold também mostraram que o **Support Vector Machine** apresentou o melhor desempenho médio entre os modelos avaliados, além de manter valores altos e relativamente consistentes ao longo das cinco partições. Dessa forma, a validação cruzada indicou que o **SVM** foi o classificador com melhor resultado geral nesta etapa, tornando-se o principal candidato para a etapa de refinamento.

## **Passo 9: Refinar modelos e ajustar hiperparâmetros**
Objetivo: Ajustar os hiperparâmetros dos classificadores, buscando melhorar seus resultados por meio de validação cruzada.

**9.1 Árvore de Decisão**
"""

# ==============================
# Passo 9: Refinar modelos e ajustar hiperparâmetros
# ==============================

# 9.1 Árvore de Decisão

pipeline_dt_ref = Pipeline([
    ('model', DecisionTreeClassifier(random_state=42))
])

param_grid_dt = {
    'model__criterion': ['gini', 'entropy'],
    'model__max_depth': [None, 5, 10, 15, 20],
    'model__min_samples_split': [2, 5, 10],
    'model__min_samples_leaf': [1, 2, 4]
}

grid_dt = GridSearchCV(
    estimator=pipeline_dt_ref,
    param_grid=param_grid_dt,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_dt.fit(X_train, y_train)
best_dt_model = grid_dt.best_estimator_
y_pred_best_dt = best_dt_model.predict(X_test)

accuracy_best_dt = accuracy_score(y_test, y_pred_best_dt)
classification_rep_best_dt = classification_report(y_test, y_pred_best_dt, zero_division=0)
conf_matrix_best_dt = confusion_matrix(y_test, y_pred_best_dt)

print("Melhores parâmetros encontrados para Árvore de Decisão:")
print(grid_dt.best_params_)
print('-----------------------')
print(f"Acurácia (Árvore de Decisão Refinada): {accuracy_best_dt:.4f}")
print("Relatório de Classificação (Árvore de Decisão Refinada):")
print(classification_rep_best_dt)
print("Matriz de Confusão (Árvore de Decisão Refinada):")
print(conf_matrix_best_dt)
print('=======================')

"""**9.2 K-Nearest Neighbor**"""

# 9.2 K-Nearest Neighbor

pipeline_knn_ref = Pipeline([
    ('scaler', StandardScaler()),
    ('model', KNeighborsClassifier())
])

param_grid_knn = {
    'model__n_neighbors': [3, 5, 7, 9, 11, 13],
    'model__weights': ['uniform', 'distance'],
    'model__metric': ['euclidean', 'manhattan']
}

grid_knn = GridSearchCV(
    estimator=pipeline_knn_ref,
    param_grid=param_grid_knn,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_knn.fit(X_train, y_train)
best_knn_model = grid_knn.best_estimator_
y_pred_best_knn = best_knn_model.predict(X_test)

accuracy_best_knn = accuracy_score(y_test, y_pred_best_knn)
classification_rep_best_knn = classification_report(y_test, y_pred_best_knn, zero_division=0)
conf_matrix_best_knn = confusion_matrix(y_test, y_pred_best_knn)

print("Melhores parâmetros encontrados para K-Nearest Neighbor:")
print(grid_knn.best_params_)
print('-----------------------')
print(f"Acurácia (K-Nearest Neighbor Refinado): {accuracy_best_knn:.4f}")
print("Relatório de Classificação (K-Nearest Neighbor Refinado):")
print(classification_rep_best_knn)
print("Matriz de Confusão (K-Nearest Neighbor Refinado):")
print(conf_matrix_best_knn)
print('=======================')

"""**9.3 Random Forest**"""

# 9.3 Random Forest

pipeline_rf_ref = Pipeline([
    ('model', RandomForestClassifier(random_state=42))
])

param_grid_rf = {
    'model__n_estimators': [100, 200],
    'model__max_depth': [None, 10, 20],
    'model__min_samples_split': [2, 5],
    'model__min_samples_leaf': [1, 2]
}

grid_rf = GridSearchCV(
    estimator=pipeline_rf_ref,
    param_grid=param_grid_rf,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_rf.fit(X_train, y_train)
best_rf_model = grid_rf.best_estimator_
y_pred_best_rf = best_rf_model.predict(X_test)

accuracy_best_rf = accuracy_score(y_test, y_pred_best_rf)
classification_rep_best_rf = classification_report(y_test, y_pred_best_rf, zero_division=0)
conf_matrix_best_rf = confusion_matrix(y_test, y_pred_best_rf)

print("Melhores parâmetros encontrados para Random Forest:")
print(grid_rf.best_params_)
print('-----------------------')
print(f"Acurácia (Random Forest Refinado): {accuracy_best_rf:.4f}")
print("Relatório de Classificação (Random Forest Refinado):")
print(classification_rep_best_rf)
print("Matriz de Confusão (Random Forest Refinado):")
print(conf_matrix_best_rf)
print('=======================')

"""**9.4 Support Vector Machine**"""

# 9.4 Support Vector Machine

pipeline_svm_ref = Pipeline([
    ('scaler', StandardScaler()),
    ('model', SVC(random_state=42))
])

param_grid_svm = {
    'model__C': [0.1, 1, 10],
    'model__kernel': ['linear', 'rbf'],
    'model__gamma': ['scale', 'auto']
}

grid_svm = GridSearchCV(
    estimator=pipeline_svm_ref,
    param_grid=param_grid_svm,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid_svm.fit(X_train, y_train)
best_svm_model = grid_svm.best_estimator_
y_pred_best_svm = best_svm_model.predict(X_test)

accuracy_best_svm = accuracy_score(y_test, y_pred_best_svm)
classification_rep_best_svm = classification_report(y_test, y_pred_best_svm, zero_division=0)
conf_matrix_best_svm = confusion_matrix(y_test, y_pred_best_svm)

print("Melhores parâmetros encontrados para Support Vector Machine:")
print(grid_svm.best_params_)
print('-----------------------')
print(f"Acurácia (Support Vector Machine Refinado): {accuracy_best_svm:.4f}")
print("Relatório de Classificação (Support Vector Machine Refinado):")
print(classification_rep_best_svm)
print("Matriz de Confusão (Support Vector Machine Refinado):")
print(conf_matrix_best_svm)
print('=======================')

"""**Comparando resultados após refinamento**"""

# Comparação antes e depois do refinamento

modelos_refinamento = [
    'Árvore de Decisão',
    'K-Nearest Neighbor',
    'Random Forest',
    'Support Vector Machine'
]

acuracia_antes = [
    accuracy_dt,
    accuracy_knn,
    accuracy_rf,
    accuracy_svm
]

acuracia_depois = [
    accuracy_best_dt,
    accuracy_best_knn,
    accuracy_best_rf,
    accuracy_best_svm
]

x = np.arange(len(modelos_refinamento))
largura = 0.35

plt.figure(figsize=(12, 6))
plt.bar(x - largura/2, acuracia_antes, largura, label='Antes do refinamento')
plt.bar(x + largura/2, acuracia_depois, largura, label='Depois do refinamento')

plt.xticks(x, modelos_refinamento, rotation=20)
plt.ylabel('Acurácia')
plt.title('Comparação dos resultados antes e depois do refinamento')
plt.ylim(0, 1)

for i, v in enumerate(acuracia_antes):
    plt.text(i - largura/2, v, f'{v:.4f}', ha='center', va='bottom')

for i, v in enumerate(acuracia_depois):
    plt.text(i + largura/2, v, f'{v:.4f}', ha='center', va='bottom')

plt.legend()
plt.show()

"""**Conclusão:**

Nesta etapa, foram realizados ajustes de hiperparâmetros em quatro classificadores: Árvore de Decisão, K-Nearest Neighbor, Random Forest e Support Vector Machine. Para isso, foi utilizado o GridSearchCV com validação cruzada 5-fold, permitindo testar diferentes combinações de parâmetros e selecionar automaticamente as configurações com melhor desempenho no conjunto de treino.

Após o refinamento, os modelos ajustados foram avaliados no conjunto de teste, possibilitando identificar qual deles apresentou o melhor resultado final no problema de previsão de churn. Com base nas acurácias obtidas após o ajuste, a classificação dos modelos refinados ficou organizada da seguinte forma:

1. **Support Vector Machine Refinado** — acurácia de **0,8045**
2. **Random Forest Refinado** — acurácia de **0,8021**
3. **Árvore de Decisão Refinada** — acurácia de **0,7888**
4. **K-Nearest Neighbor Refinado** — acurácia de **0,7855**

Além da maior acurácia, o **Support Vector Machine Refinado** também apresentou resultados equilibrados para a classe positiva, com **precision de 0,66**, **recall de 0,54** e **f1-score de 0,59**, mostrando bom desempenho na identificação dos clientes que cancelaram o serviço. O **Random Forest Refinado** também apresentou resultado competitivo, com acurácia muito próxima (**0,8021**) e métricas semelhantes para a classe positiva.

Já a **Árvore de Decisão Refinada** e o **K-Nearest Neighbor Refinado** apresentaram desempenho inferior aos dois melhores modelos, embora ambos tenham melhorado sua capacidade preditiva em relação às versões iniciais.

Dessa forma, conclui-se que o refinamento dos hiperparâmetros contribuiu para melhorar o desempenho dos classificadores e identificar configurações mais adequadas para o problema. Entre os modelos refinados, o **Support Vector Machine** apresentou o melhor desempenho final, tornando-se o melhor modelo desta etapa.

## **Passo 10: Conclusão final**
"""

# ==============================
# Passo 10: Conclusão final
# ==============================

resultados_base_completa = pd.DataFrame({
    'Modelo': [
        'Árvore de Decisão',
        'K-Nearest Neighbor',
        'Random Forest',
        'Support Vector Machine'
    ],
    'Acurácia': [
        accuracy_dt,
        accuracy_knn,
        accuracy_rf,
        accuracy_svm
    ]
}).sort_values(by='Acurácia', ascending=False).reset_index(drop=True)

resultados_refinados = pd.DataFrame({
    'Modelo': [
        'Árvore de Decisão',
        'K-Nearest Neighbor',
        'Random Forest',
        'Support Vector Machine'
    ],
    'Acurácia': [
        accuracy_best_dt,
        accuracy_best_knn,
        accuracy_best_rf,
        accuracy_best_svm
    ]
}).sort_values(by='Acurácia', ascending=False).reset_index(drop=True)

print("Ranking dos modelos antes do refinamento:")
print(resultados_base_completa)
print('-----------------------')

print("Ranking dos modelos após o refinamento:")
print(resultados_refinados)
print('-----------------------')

melhor_modelo_base_completa = resultados_base_completa.iloc[0]
melhor_modelo_refinado = resultados_refinados.iloc[0]

print(
    f"Melhor modelo antes do refinamento: {melhor_modelo_base_completa['Modelo']} "
    f"com acurácia de {melhor_modelo_base_completa['Acurácia']:.4f}"
)
print('-----------------------')

print(
    f"Melhor modelo após o refinamento: {melhor_modelo_refinado['Modelo']} "
    f"com acurácia de {melhor_modelo_refinado['Acurácia']:.4f}"
)
print('-----------------------')

# Comparação direta antes x depois
comparacao_final = pd.DataFrame({
    'Modelo': [
        'Árvore de Decisão',
        'K-Nearest Neighbor',
        'Random Forest',
        'Support Vector Machine'
    ],
    'Acurácia Antes': [
        accuracy_dt,
        accuracy_knn,
        accuracy_rf,
        accuracy_svm
    ],
    'Acurácia Depois': [
        accuracy_best_dt,
        accuracy_best_knn,
        accuracy_best_rf,
        accuracy_best_svm
    ]
})

comparacao_final['Diferença'] = comparacao_final['Acurácia Depois'] - comparacao_final['Acurácia Antes']
comparacao_final = comparacao_final.sort_values(by='Acurácia Depois', ascending=False).reset_index(drop=True)

print("Comparação final entre os modelos:")
print(comparacao_final)
print('-----------------------')

print("Conclusão:")
print(
    "Nesta atividade, foram avaliados cinco classificadores para prever o churn de clientes: "
    "Árvore de Decisão, K-Nearest Neighbor, Random Forest e Support Vector Machine. "
    "Inicialmente, os modelos foram treinados e avaliados com a base preparada, permitindo comparar seus desempenhos "
    "por meio das métricas de acurácia, relatório de classificação e matriz de confusão. "
    "Em seguida, foi realizada a validação cruzada com 5 folds, o que possibilitou uma avaliação mais robusta dos modelos. "
    "Na etapa final, os cinco classificadores foram refinados com ajuste de hiperparâmetros por meio do GridSearchCV, "
    "permitindo verificar se houve ganho de desempenho em relação às versões iniciais. "
    f"Antes do refinamento, o melhor modelo foi {melhor_modelo_base_completa['Modelo']} "
    f"com acurácia de {melhor_modelo_base_completa['Acurácia']:.4f}. "
    f"Após o refinamento, o melhor desempenho foi obtido por {melhor_modelo_refinado['Modelo']} "
    f"com acurácia de {melhor_modelo_refinado['Acurácia']:.4f}. "
    "Dessa forma, o modelo com melhor resultado final pode ser considerado o mais adequado para o problema de previsão de churn nesta base analisada."
)